# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p4sfcstate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='p4sfcstate.proto',
  package='P4SFCState',
  syntax='proto3',
  serialized_pb=_b('\n\x10p4sfcstate.proto\x12\nP4SFCState\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"m\n\x0fTableEntryReply\x12\x19\n\x11\x63lick_instance_id\x18\x01 \x01(\x05\x12\x16\n\x0ewindow_cur_pos\x18\x02 \x01(\x05\x12\'\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x16.P4SFCState.TableEntry\"\xa8\x01\n\nTableEntry\x12\x12\n\ntable_name\x18\x01 \x01(\x0c\x12%\n\x05match\x18\x02 \x03(\x0b\x32\x16.P4SFCState.FieldMatch\x12\"\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x12.P4SFCState.Action\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12)\n\x06window\x18\x05 \x01(\x0b\x32\x19.P4SFCState.SlidingWindow\"\x1d\n\rSlidingWindow\x12\x0c\n\x04slot\x18\x01 \x03(\x03\"\xd6\x01\n\nFieldMatch\x12\x12\n\nfield_name\x18\x01 \x01(\t\x12-\n\x05\x65xact\x18\x02 \x01(\x0b\x32\x1c.P4SFCState.FieldMatch.ExactH\x00\x12\x31\n\x07ternary\x18\x03 \x01(\x0b\x32\x1e.P4SFCState.FieldMatch.TernaryH\x00\x1a\x16\n\x05\x45xact\x12\r\n\x05value\x18\x01 \x01(\x0c\x1a&\n\x07Ternary\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x0c\n\x04mask\x18\x02 \x01(\x0c\x42\x12\n\x10\x66ield_match_type\"i\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12(\n\x06params\x18\x04 \x03(\x0b\x32\x18.P4SFCState.Action.Param\x1a%\n\x05Param\x12\r\n\x05param\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\x32\xc4\x01\n\x03RPC\x12>\n\x08SayHello\x12\x18.P4SFCState.HelloRequest\x1a\x16.P4SFCState.HelloReply\"\x00\x12<\n\x08GetState\x12\x11.P4SFCState.Empty\x1a\x1b.P4SFCState.TableEntryReply\"\x00\x12?\n\x0bGetNewState\x12\x11.P4SFCState.Empty\x1a\x1b.P4SFCState.TableEntryReply\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='P4SFCState.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='P4SFCState.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=60,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='P4SFCState.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='P4SFCState.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='P4SFCState.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=100,
)


_TABLEENTRYREPLY = _descriptor.Descriptor(
  name='TableEntryReply',
  full_name='P4SFCState.TableEntryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='click_instance_id', full_name='P4SFCState.TableEntryReply.click_instance_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='window_cur_pos', full_name='P4SFCState.TableEntryReply.window_cur_pos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entries', full_name='P4SFCState.TableEntryReply.entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=211,
)


_TABLEENTRY = _descriptor.Descriptor(
  name='TableEntry',
  full_name='P4SFCState.TableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='P4SFCState.TableEntry.table_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='match', full_name='P4SFCState.TableEntry.match', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='P4SFCState.TableEntry.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='P4SFCState.TableEntry.priority', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='window', full_name='P4SFCState.TableEntry.window', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=382,
)


_SLIDINGWINDOW = _descriptor.Descriptor(
  name='SlidingWindow',
  full_name='P4SFCState.SlidingWindow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slot', full_name='P4SFCState.SlidingWindow.slot', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=413,
)


_FIELDMATCH_EXACT = _descriptor.Descriptor(
  name='Exact',
  full_name='P4SFCState.FieldMatch.Exact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='P4SFCState.FieldMatch.Exact.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=570,
)

_FIELDMATCH_TERNARY = _descriptor.Descriptor(
  name='Ternary',
  full_name='P4SFCState.FieldMatch.Ternary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='P4SFCState.FieldMatch.Ternary.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask', full_name='P4SFCState.FieldMatch.Ternary.mask', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=610,
)

_FIELDMATCH = _descriptor.Descriptor(
  name='FieldMatch',
  full_name='P4SFCState.FieldMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_name', full_name='P4SFCState.FieldMatch.field_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exact', full_name='P4SFCState.FieldMatch.exact', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ternary', full_name='P4SFCState.FieldMatch.ternary', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FIELDMATCH_EXACT, _FIELDMATCH_TERNARY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='field_match_type', full_name='P4SFCState.FieldMatch.field_match_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=416,
  serialized_end=630,
)


_ACTION_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='P4SFCState.Action.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param', full_name='P4SFCState.Action.Param.param', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='P4SFCState.Action.Param.value', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=737,
)

_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='P4SFCState.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='P4SFCState.Action.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='P4SFCState.Action.params', index=1,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTION_PARAM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=737,
)

_TABLEENTRYREPLY.fields_by_name['entries'].message_type = _TABLEENTRY
_TABLEENTRY.fields_by_name['match'].message_type = _FIELDMATCH
_TABLEENTRY.fields_by_name['action'].message_type = _ACTION
_TABLEENTRY.fields_by_name['window'].message_type = _SLIDINGWINDOW
_FIELDMATCH_EXACT.containing_type = _FIELDMATCH
_FIELDMATCH_TERNARY.containing_type = _FIELDMATCH
_FIELDMATCH.fields_by_name['exact'].message_type = _FIELDMATCH_EXACT
_FIELDMATCH.fields_by_name['ternary'].message_type = _FIELDMATCH_TERNARY
_FIELDMATCH.oneofs_by_name['field_match_type'].fields.append(
  _FIELDMATCH.fields_by_name['exact'])
_FIELDMATCH.fields_by_name['exact'].containing_oneof = _FIELDMATCH.oneofs_by_name['field_match_type']
_FIELDMATCH.oneofs_by_name['field_match_type'].fields.append(
  _FIELDMATCH.fields_by_name['ternary'])
_FIELDMATCH.fields_by_name['ternary'].containing_oneof = _FIELDMATCH.oneofs_by_name['field_match_type']
_ACTION_PARAM.containing_type = _ACTION
_ACTION.fields_by_name['params'].message_type = _ACTION_PARAM
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['TableEntryReply'] = _TABLEENTRYREPLY
DESCRIPTOR.message_types_by_name['TableEntry'] = _TABLEENTRY
DESCRIPTOR.message_types_by_name['SlidingWindow'] = _SLIDINGWINDOW
DESCRIPTOR.message_types_by_name['FieldMatch'] = _FIELDMATCH
DESCRIPTOR.message_types_by_name['Action'] = _ACTION

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.Empty)
  ))
_sym_db.RegisterMessage(Empty)

TableEntryReply = _reflection.GeneratedProtocolMessageType('TableEntryReply', (_message.Message,), dict(
  DESCRIPTOR = _TABLEENTRYREPLY,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.TableEntryReply)
  ))
_sym_db.RegisterMessage(TableEntryReply)

TableEntry = _reflection.GeneratedProtocolMessageType('TableEntry', (_message.Message,), dict(
  DESCRIPTOR = _TABLEENTRY,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.TableEntry)
  ))
_sym_db.RegisterMessage(TableEntry)

SlidingWindow = _reflection.GeneratedProtocolMessageType('SlidingWindow', (_message.Message,), dict(
  DESCRIPTOR = _SLIDINGWINDOW,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.SlidingWindow)
  ))
_sym_db.RegisterMessage(SlidingWindow)

FieldMatch = _reflection.GeneratedProtocolMessageType('FieldMatch', (_message.Message,), dict(

  Exact = _reflection.GeneratedProtocolMessageType('Exact', (_message.Message,), dict(
    DESCRIPTOR = _FIELDMATCH_EXACT,
    __module__ = 'p4sfcstate_pb2'
    # @@protoc_insertion_point(class_scope:P4SFCState.FieldMatch.Exact)
    ))
  ,

  Ternary = _reflection.GeneratedProtocolMessageType('Ternary', (_message.Message,), dict(
    DESCRIPTOR = _FIELDMATCH_TERNARY,
    __module__ = 'p4sfcstate_pb2'
    # @@protoc_insertion_point(class_scope:P4SFCState.FieldMatch.Ternary)
    ))
  ,
  DESCRIPTOR = _FIELDMATCH,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.FieldMatch)
  ))
_sym_db.RegisterMessage(FieldMatch)
_sym_db.RegisterMessage(FieldMatch.Exact)
_sym_db.RegisterMessage(FieldMatch.Ternary)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(

  Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), dict(
    DESCRIPTOR = _ACTION_PARAM,
    __module__ = 'p4sfcstate_pb2'
    # @@protoc_insertion_point(class_scope:P4SFCState.Action.Param)
    ))
  ,
  DESCRIPTOR = _ACTION,
  __module__ = 'p4sfcstate_pb2'
  # @@protoc_insertion_point(class_scope:P4SFCState.Action)
  ))
_sym_db.RegisterMessage(Action)
_sym_db.RegisterMessage(Action.Param)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class RPCStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SayHello = channel.unary_unary(
          '/P4SFCState.RPC/SayHello',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloReply.FromString,
          )
      self.GetState = channel.unary_unary(
          '/P4SFCState.RPC/GetState',
          request_serializer=Empty.SerializeToString,
          response_deserializer=TableEntryReply.FromString,
          )
      self.GetNewState = channel.unary_unary(
          '/P4SFCState.RPC/GetNewState',
          request_serializer=Empty.SerializeToString,
          response_deserializer=TableEntryReply.FromString,
          )


  class RPCServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
      """Sends a greeting for test
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetNewState(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_RPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SayHello': grpc.unary_unary_rpc_method_handler(
            servicer.SayHello,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloReply.SerializeToString,
        ),
        'GetState': grpc.unary_unary_rpc_method_handler(
            servicer.GetState,
            request_deserializer=Empty.FromString,
            response_serializer=TableEntryReply.SerializeToString,
        ),
        'GetNewState': grpc.unary_unary_rpc_method_handler(
            servicer.GetNewState,
            request_deserializer=Empty.FromString,
            response_serializer=TableEntryReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'P4SFCState.RPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaRPCServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def SayHello(self, request, context):
      """Sends a greeting for test
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetState(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetNewState(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaRPCStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def SayHello(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends a greeting for test
      """
      raise NotImplementedError()
    SayHello.future = None
    def GetState(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetState.future = None
    def GetNewState(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetNewState.future = None


  def beta_create_RPC_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('P4SFCState.RPC', 'GetNewState'): Empty.FromString,
      ('P4SFCState.RPC', 'GetState'): Empty.FromString,
      ('P4SFCState.RPC', 'SayHello'): HelloRequest.FromString,
    }
    response_serializers = {
      ('P4SFCState.RPC', 'GetNewState'): TableEntryReply.SerializeToString,
      ('P4SFCState.RPC', 'GetState'): TableEntryReply.SerializeToString,
      ('P4SFCState.RPC', 'SayHello'): HelloReply.SerializeToString,
    }
    method_implementations = {
      ('P4SFCState.RPC', 'GetNewState'): face_utilities.unary_unary_inline(servicer.GetNewState),
      ('P4SFCState.RPC', 'GetState'): face_utilities.unary_unary_inline(servicer.GetState),
      ('P4SFCState.RPC', 'SayHello'): face_utilities.unary_unary_inline(servicer.SayHello),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_RPC_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('P4SFCState.RPC', 'GetNewState'): Empty.SerializeToString,
      ('P4SFCState.RPC', 'GetState'): Empty.SerializeToString,
      ('P4SFCState.RPC', 'SayHello'): HelloRequest.SerializeToString,
    }
    response_deserializers = {
      ('P4SFCState.RPC', 'GetNewState'): TableEntryReply.FromString,
      ('P4SFCState.RPC', 'GetState'): TableEntryReply.FromString,
      ('P4SFCState.RPC', 'SayHello'): HelloReply.FromString,
    }
    cardinalities = {
      'GetNewState': cardinality.Cardinality.UNARY_UNARY,
      'GetState': cardinality.Cardinality.UNARY_UNARY,
      'SayHello': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'P4SFCState.RPC', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
